## Imports:

In [1]:
import scipy.io
import os
import pandas
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.pylab as plt_lab
import matplotlib.gridspec as gridspec
import obspy
import pandas as pd

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

In [2]:
import warnings
warnings.filterwarnings('ignore')

## Load data:
We are going to use this data to plot spectograms of SCG signals.

In [3]:
path = "/Users/ecem/Desktop/phonocardiogram/data/AV/"

In [6]:
csv = pd.read_csv("/Users/ecem/Desktop/phonocardiogram/data/training_data.csv")

In [7]:
csv.head()

,Patient ID,Recording locations:,Age,Sex,Height,Weight,Pregnancy status,Murmur,Murmur locations,Most audible location,...,Systolic murmur pitch,Systolic murmur quality,Diastolic murmur timing,Diastolic murmur shape,Diastolic murmur grading,Diastolic murmur pitch,Diastolic murmur quality,Outcome,Campaign,Additional ID
0,2530,AV+PV+TV+MV,Child,Female,98.0,15.9,False,Absent,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Abnormal,CC2015,NaN
1,9979,AV+PV+TV+MV,Child,Female,103.0,13.1,False,Present,AV+MV+PV+TV,TV,...,High,Harsh,NaN,NaN,NaN,NaN,NaN,Abnormal,CC2015,NaN
2,9983,AV+PV+TV+MV,Child,Male,115.0,19.1,False,Unknown,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Abnormal,CC2015,NaN
3,13918,AV+PV+TV+MV,Child,Male,98.0,15.9,False,Present,TV,TV,...,Low,Blowing,NaN,NaN,NaN,NaN,NaN,Abnormal,CC2015,NaN
4,14241,AV+PV+TV+MV,Child,Male,87.0,11.2,False,Present,AV+MV+PV+TV,PV,...,Low,Harsh,NaN,NaN,NaN,NaN,NaN,Abnormal,CC2015,NaN

## manipulate the csv

### split recording locations

In [8]:
recording_locations = csv["Recording locations:"].str.split("+", n = 3, expand = True)
recording_locations

      0   1     2     3
0    AV  PV    TV    MV
1    AV  PV    TV    MV
2    AV  PV    TV    MV
3    AV  PV    TV    MV
4    AV  PV    TV    MV
..   ..  ..   ...   ...
937  AV  PV    TV    MV
938  AV  PV    TV    MV
939  AV  PV    TV    MV
940  AV  PV  None  None
941  AV  PV    TV  None

[942 rows x 4 columns]

In [9]:
recordings = np.zeros(shape=(942, 4))

In [10]:
for i in range(942):
    if recording_locations.iloc[i][0] == 'AV':
        recordings[i][0] = 1
        
    if recording_locations.iloc[i][1] == 'PV':
        recordings[i][2] = 1
        
    if recording_locations.iloc[i][2] == 'TV':
        recordings[i][3] = 1
        
    if recording_locations.iloc[i][3] == 'MV':
        recordings[i][1] = 1

In [11]:
recordings

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       ...,
       [1., 1., 1., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 1.]])

### split murmur present locations

In [12]:
murmur_location = csv["Murmur locations"].str.split("+",  n = 3, expand = True)
murmur_location

       0     1     2     3
0    NaN   NaN   NaN   NaN
1     AV    MV    PV    TV
2    NaN   NaN   NaN   NaN
3     TV  None  None  None
4     AV    MV    PV    TV
..   ...   ...   ...   ...
937  NaN   NaN   NaN   NaN
938  NaN   NaN   NaN   NaN
939   MV    TV  None  None
940  NaN   NaN   NaN   NaN
941  NaN   NaN   NaN   NaN

[942 rows x 4 columns]

In [13]:
murmur_0 = np.zeros(shape=(942, 4))
murmur_1 = np.zeros(shape=(942, 4))
murmur_2 = np.zeros(shape=(942, 4))
murmur_3 = np.zeros(shape=(942, 4))

In [14]:
for i in range(len(csv)):
    if murmur_location.iloc[i][0] == 'AV':
        murmur_0[i][0] = 1
    if murmur_location.iloc[i][0] == 'MV':
        murmur_0[i][1] = 1
    if murmur_location.iloc[i][0] == 'PV':
        murmur_0[i][2] = 1
    if murmur_location.iloc[i][0] == 'TV':
        murmur_0[i][3] = 1

In [15]:
murmur_0

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       ...,
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
for i in range(len(csv)):
    if murmur_location.iloc[i][1] == 'AV':
        murmur_1[i][0] = 1
        
    if murmur_location.iloc[i][1] == 'MV':
        murmur_1[i][1] = 1
        
    if murmur_location.iloc[i][1] == 'PV':
        murmur_1[i][2] = 1
        
    if murmur_location.iloc[i][1] == 'TV':
        murmur_1[i][3] = 1
        
murmur_1

array([[0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
for i in range(len(csv)):
    if murmur_location.iloc[i][2] == 'AV':
        murmur_2[i][0] = 1
        
    if murmur_location.iloc[i][2] == 'MV':
        murmur_2[i][1] = 1
        
    if murmur_location.iloc[i][2] == 'PV':
        murmur_2[i][2] = 1
        
    if murmur_location.iloc[i][2] == 'TV':
        murmur_2[i][3] = 1
        
murmur_2

array([[0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
for i in range(len(csv)):
    if murmur_location.iloc[i][3] == 'AV':
        murmur_3[i][0] = 1
        
    if murmur_location.iloc[i][3] == 'MV':
        murmur_3[i][1] = 1
        
    if murmur_location.iloc[i][3] == 'PV':
        murmur_3[i][2] = 1
        
    if murmur_location.iloc[i][3] == 'TV':
        murmur_3[i][3] = 1
        
murmur_3

array([[0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
murmur = murmur_0 + murmur_1 + murmur_2 + murmur_3

In [20]:
murmur

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       ...,
       [0., 1., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### create their dataframe

In [21]:
recording_df = pd.DataFrame(recordings, columns =['recording location AV', 'recording location MV'
                                                        , 'recording location PV', 'recording location TV'])
recording_df

,recording location AV,recording location MV,recording location PV,recording location TV
0,1.0,1.0,1.0,1.0
1,1.0,1.0,1.0,1.0
2,1.0,1.0,1.0,1.0
3,1.0,1.0,1.0,1.0
4,1.0,1.0,1.0,1.0
...,...,...,...,...
937,1.0,1.0,1.0,1.0
938,1.0,1.0,1.0,1.0
939,1.0,1.0,1.0,1.0
940,1.0,0.0,1.0,0.0
941,1.0,0.0,1.0,1.0

In [22]:
murmur_df = pd.DataFrame(murmur, columns =['murmur location AV', 'murmur location MV'
                                                        , 'murmur location PV', 'murmur location TV'])
murmur_df

,murmur location AV,murmur location MV,murmur location PV,murmur location TV
0,0.0,0.0,0.0,0.0
1,1.0,1.0,1.0,1.0
2,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0
4,1.0,1.0,1.0,1.0
...,...,...,...,...
937,0.0,0.0,0.0,0.0
938,0.0,0.0,0.0,0.0
939,0.0,1.0,0.0,1.0
940,0.0,0.0,0.0,0.0
941,0.0,0.0,0.0,0.0

### drop recording  locations and murmr locaitons and append new columns

In [23]:
csv.drop(['Recording locations:', 'Murmur locations'], axis =1,  inplace = True)

In [24]:
csv

,Patient ID,Age,Sex,Height,Weight,Pregnancy status,Murmur,Most audible location,Systolic murmur timing,Systolic murmur shape,...,Systolic murmur pitch,Systolic murmur quality,Diastolic murmur timing,Diastolic murmur shape,Diastolic murmur grading,Diastolic murmur pitch,Diastolic murmur quality,Outcome,Campaign,Additional ID
0,2530,Child,Female,98.0,15.9,False,Absent,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Abnormal,CC2015,NaN
1,9979,Child,Female,103.0,13.1,False,Present,TV,Holosystolic,Diamond,...,High,Harsh,NaN,NaN,NaN,NaN,NaN,Abnormal,CC2015,NaN
2,9983,Child,Male,115.0,19.1,False,Unknown,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Abnormal,CC2015,NaN
3,13918,Child,Male,98.0,15.9,False,Present,TV,Holosystolic,Plateau,...,Low,Blowing,NaN,NaN,NaN,NaN,NaN,Abnormal,CC2015,NaN
4,14241,Child,Male,87.0,11.2,False,Present,PV,Early-systolic,Plateau,...,Low,Harsh,NaN,NaN,NaN,NaN,NaN,Abnormal,CC2015,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,85340,Child,Male,105.0,16.6,False,Absent,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,CC2015,NaN
938,85341,Child,Male,92.0,15.2,False,Absent,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,CC2015,NaN
939,85343,Child,Female,97.0,13.5,False,Present,TV,Early-systolic,Plateau,...,Low,Blowing,NaN,NaN,NaN,NaN,NaN,Abnormal,CC2015,NaN
940,85345,Child,Female,132.0,38.1,False,Absent,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,CC2015,NaN
941,85349,NaN,Female,NaN,NaN,True,Absent,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,CC2015,NaN

In [25]:
csv = pd.concat([csv, recording_df, murmur_df], axis = 1 )
csv

,Patient ID,Age,Sex,Height,Weight,Pregnancy status,Murmur,Most audible location,Systolic murmur timing,Systolic murmur shape,...,Campaign,Additional ID,recording location AV,recording location MV,recording location PV,recording location TV,murmur location AV,murmur location MV,murmur location PV,murmur location TV
0,2530,Child,Female,98.0,15.9,False,Absent,NaN,NaN,NaN,...,CC2015,NaN,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
1,9979,Child,Female,103.0,13.1,False,Present,TV,Holosystolic,Diamond,...,CC2015,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,9983,Child,Male,115.0,19.1,False,Unknown,NaN,NaN,NaN,...,CC2015,NaN,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
3,13918,Child,Male,98.0,15.9,False,Present,TV,Holosystolic,Plateau,...,CC2015,NaN,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0
4,14241,Child,Male,87.0,11.2,False,Present,PV,Early-systolic,Plateau,...,CC2015,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,85340,Child,Male,105.0,16.6,False,Absent,NaN,NaN,NaN,...,CC2015,NaN,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
938,85341,Child,Male,92.0,15.2,False,Absent,NaN,NaN,NaN,...,CC2015,NaN,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
939,85343,Child,Female,97.0,13.5,False,Present,TV,Early-systolic,Plateau,...,CC2015,NaN,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
940,85345,Child,Female,132.0,38.1,False,Absent,NaN,NaN,NaN,...,CC2015,NaN,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
941,85349,NaN,Female,NaN,NaN,True,Absent,NaN,NaN,NaN,...,CC2015,NaN,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0

### now get index values of  the rows with Murmur == present, absent,unknown

In [26]:
idx_unknown  = np.where(csv['Murmur'] == 'Unknown')
idx_unknown

(array([  2,   9,  16,  28,  38,  40,  46,  51,  65, 126, 165, 171, 189,
        208, 225, 255, 257, 271, 301, 302, 307, 309, 397, 426, 439, 445,
        447, 484, 487, 508, 510, 514, 524, 526, 549, 556, 559, 589, 600,
        605, 606, 612, 618, 652, 672, 682, 685, 689, 693, 702, 712, 729,
        730, 734, 740, 766, 784, 832, 850, 854, 858, 859, 871, 872, 908,
        911, 921, 923]),)

In [27]:
idx_present = np.where((csv['Murmur'] == 'Present'))
idx_present

(array([  1,   3,   4,   8,  11,  12,  19,  21,  22,  23,  25,  26,  27,
         32,  33,  36,  42,  43,  44,  55,  57,  62,  63,  64,  68,  69,
         70,  73,  76,  82,  83,  85,  91, 103, 106, 135, 136, 156, 164,
        167, 174, 176, 178, 180, 186, 187, 192, 194, 203, 211, 212, 216,
        219, 220, 231, 232, 233, 242, 244, 247, 248, 265, 269, 272, 273,
        304, 320, 332, 358, 359, 360, 367, 368, 377, 389, 395, 414, 416,
        417, 418, 420, 424, 429, 430, 434, 437, 440, 441, 446, 449, 451,
        453, 462, 463, 466, 467, 469, 471, 479, 485, 486, 488, 498, 502,
        515, 527, 528, 529, 531, 534, 539, 541, 548, 551, 555, 557, 558,
        567, 571, 572, 573, 574, 578, 586, 588, 594, 596, 609, 628, 634,
        650, 655, 658, 659, 662, 665, 666, 667, 678, 681, 688, 705, 711,
        743, 744, 752, 757, 758, 762, 763, 765, 772, 773, 778, 782, 783,
        787, 798, 800, 807, 815, 816, 818, 824, 839, 843, 844, 856, 857,
        860, 867, 881, 891, 892, 896, 898, 914, 936, 939]),)

In [28]:
idx_absent = np.where((csv['Murmur'] == 'Absent'))
idx_absent

(array([  0,   5,   6,   7,  10,  13,  14,  15,  17,  18,  20,  24,  29,
         30,  31,  34,  35,  37,  39,  41,  45,  47,  48,  49,  50,  52,
         53,  54,  56,  58,  59,  60,  61,  66,  67,  71,  72,  74,  75,
         77,  78,  79,  80,  81,  84,  86,  87,  88,  89,  90,  92,  93,
         94,  95,  96,  97,  98,  99, 100, 101, 102, 104, 105, 107, 108,
        109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
        122, 123, 124, 125, 127, 128, 129, 130, 131, 132, 133, 134, 137,
        138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150,
        151, 152, 153, 154, 155, 157, 158, 159, 160, 161, 162, 163, 166,
        168, 169, 170, 172, 173, 175, 177, 179, 181, 182, 183, 184, 185,
        188, 190, 191, 193, 195, 196, 197, 198, 199, 200, 201, 202, 204,
        205, 206, 207, 209, 210, 213, 214, 215, 217, 218, 221, 222, 223,
        224, 226, 227, 228, 229, 230, 234, 235, 236, 237, 238, 239, 240,
        241, 243, 245, 246, 249, 250, 251, 252, 253, 254, 256, 258, 259,
        260, 261, 262, 263, 264, 266, 267, 268, 270, 274, 275, 276, 277,
        278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290,
        291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 303, 305, 306,
        308, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 321, 322,
        323, 324, 325, 326, 327, 328, 329, 330, 331, 333, 334, 335, 336,
        337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349,
        350, 351, 352, 353, 354, 355, 356, 357, 361, 362, 363, 364, 365,
        366, 369, 370, 371, 372, 373, 374, 375, 376, 378, 379, 380, 381,
        382, 383, 384, 385, 386, 387, 388, 390, 391, 392, 393, 394, 396,
        398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410,
        411, 412, 413, 415, 419, 421, 422, 423, 425, 427, 428, 431, 432,
        433, 435, 436, 438, 442, 443, 444, 448, 450, 452, 454, 455, 456,
        457, 458, 459, 460, 461, 464, 465, 468, 470, 472, 473, 474, 475,
        476, 477, 478, 480, 481, 482, 483, 489, 490, 491, 492, 493, 494,
        495, 496, 497, 499, 500, 501, 503, 504, 505, 506, 507, 509, 511,
        512, 513, 516, 517, 518, 519, 520, 521, 522, 523, 525, 530, 532,
        533, 535, 536, 537, 538, 540, 542, 543, 544, 545, 546, 547, 550,
        552, 553, 554, 560, 561, 562, 563, 564, 565, 566, 568, 569, 570,
        575, 576, 577, 579, 580, 581, 582, 583, 584, 585, 587, 590, 591,
        592, 593, 595, 597, 598, 599, 601, 602, 603, 604, 607, 608, 610,
        611, 613, 614, 615, 616, 617, 619, 620, 621, 622, 623, 624, 625,
        626, 627, 629, 630, 631, 632, 633, 635, 636, 637, 638, 639, 640,
        641, 642, 643, 644, 645, 646, 647, 648, 649, 651, 653, 654, 656,
        657, 660, 661, 663, 664, 668, 669, 670, 671, 673, 674, 675, 676,
        677, 679, 680, 683, 684, 686, 687, 690, 691, 692, 694, 695, 696,
        697, 698, 699, 700, 701, 703, 704, 706, 707, 708, 709, 710, 713,
        714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726,
        727, 728, 731, 732, 733, 735, 736, 737, 738, 739, 741, 742, 745,
        746, 747, 748, 749, 750, 751, 753, 754, 755, 756, 759, 760, 761,
        764, 767, 768, 769, 770, 771, 774, 775, 776, 777, 779, 780, 781,
        785, 786, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 799,
        801, 802, 803, 804, 805, 806, 808, 809, 810, 811, 812, 813, 814,
        817, 819, 820, 821, 822, 823, 825, 826, 827, 828, 829, 830, 831,
        833, 834, 835, 836, 837, 838, 840, 841, 842, 845, 846, 847, 848,
        849, 851, 852, 853, 855, 861, 862, 863, 864, 865, 866, 868, 869,
        870, 873, 874, 875, 876, 877, 878, 879, 880, 882, 883, 884, 885,
        886, 887, 888, 889, 890, 893, 894, 895, 897, 899, 900, 901, 902,
        903, 904, 905, 906, 907, 909, 910, 912, 913, 915, 916, 917, 918,
        919, 920, 922, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933,
        934, 935, 937, 938, 940, 941]),)

### get indexes for recordings taken in specific location with murmur = absent, present

In [29]:
#this shows indexes of recordings taken in av location which also has a murmur at av
idx_av_present =  np.where((csv['Murmur'] == 'Present') & (csv['murmur location AV'] == 1) &
                           (csv['recording location AV'] == 1))
idx_av_present

(array([  1,   4,   8,  19,  21,  23,  33,  36,  42,  43,  55,  57,  62,
         64,  68,  70,  76,  82,  83,  85, 106, 136, 164, 176, 178, 180,
        187, 203, 211, 212, 216, 219, 220, 231, 233, 242, 244, 248, 269,
        272, 273, 304, 332, 358, 389, 395, 416, 429, 434, 440, 441, 446,
        449, 451, 453, 463, 466, 467, 469, 471, 479, 485, 488, 498, 527,
        528, 529, 531, 539, 551, 555, 558, 572, 573, 574, 586, 588, 609,
        634, 650, 659, 662, 665, 666, 667, 681, 688, 711, 743, 752, 758,
        762, 772, 773, 782, 783, 787, 800, 807, 816, 839, 843, 844, 856,
        860, 891, 892, 914]),)

In [30]:
#this shows indexes of recordings taken in av location which also has not a murmur at anywhere
idx_av_absent =  np.where((csv['Murmur'] == 'Absent') & (csv['murmur location AV'] == 0) &
                           (csv['recording location AV'] == 1))
idx_av_absent

(array([  0,   5,   6,   7,  10,  13,  14,  15,  17,  18,  20,  24,  29,
         30,  31,  34,  35,  37,  39,  41,  45,  47,  48,  49,  50,  52,
         53,  54,  56,  58,  59,  61,  66,  71,  72,  74,  75,  77,  78,
         79,  80,  81,  84,  87,  88,  89,  90,  94,  95,  98,  99, 100,
        101, 102, 104, 105, 107, 109, 110, 113, 114, 115, 116, 118, 119,
        120, 121, 122, 123, 124, 125, 128, 129, 130, 133, 134, 138, 139,
        141, 143, 144, 145, 147, 148, 149, 150, 152, 153, 155, 157, 158,
        159, 161, 162, 163, 173, 175, 181, 182, 190, 191, 196, 199, 200,
        202, 204, 205, 206, 207, 209, 210, 214, 215, 217, 218, 221, 223,
        224, 226, 227, 228, 229, 230, 234, 235, 236, 237, 238, 239, 240,
        241, 243, 246, 249, 250, 251, 252, 254, 256, 258, 260, 261, 262,
        263, 264, 266, 267, 268, 270, 274, 275, 278, 279, 280, 281, 283,
        284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 296, 297,
        300, 303, 305, 306, 311, 312, 313, 314, 315, 316, 317, 318, 319,
        321, 322, 323, 324, 325, 327, 328, 329, 331, 333, 335, 336, 337,
        338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
        352, 353, 354, 355, 357, 362, 363, 364, 365, 366, 369, 370, 371,
        372, 373, 374, 375, 376, 378, 379, 380, 381, 382, 383, 384, 385,
        386, 387, 390, 391, 393, 394, 399, 400, 401, 402, 403, 405, 406,
        407, 408, 409, 410, 411, 412, 413, 415, 419, 421, 422, 423, 427,
        428, 431, 432, 433, 435, 438, 442, 443, 444, 448, 450, 452, 457,
        458, 459, 460, 461, 464, 465, 468, 470, 472, 473, 475, 476, 477,
        478, 480, 481, 482, 483, 489, 490, 491, 492, 493, 494, 495, 496,
        497, 499, 500, 501, 503, 504, 505, 507, 509, 511, 513, 516, 517,
        518, 519, 520, 522, 523, 525, 530, 532, 533, 535, 536, 537, 538,
        540, 542, 543, 544, 545, 546, 547, 550, 552, 553, 554, 560, 561,
        563, 564, 565, 566, 568, 570, 575, 576, 577, 580, 581, 582, 583,
        584, 585, 587, 590, 591, 593, 597, 598, 599, 601, 602, 603, 604,
        607, 608, 610, 611, 613, 615, 616, 617, 621, 622, 623, 624, 625,
        626, 627, 629, 630, 631, 632, 633, 635, 637, 638, 639, 640, 641,
        642, 643, 644, 645, 646, 647, 648, 649, 651, 653, 654, 656, 657,
        661, 663, 664, 668, 669, 670, 671, 673, 674, 675, 676, 677, 679,
        680, 683, 684, 686, 687, 690, 691, 694, 695, 696, 697, 698, 699,
        700, 701, 703, 704, 706, 707, 708, 709, 710, 713, 714, 715, 716,
        717, 718, 719, 721, 723, 724, 725, 726, 727, 728, 731, 732, 733,
        735, 736, 737, 738, 739, 741, 742, 745, 746, 747, 748, 749, 750,
        751, 753, 754, 755, 756, 759, 760, 761, 764, 767, 768, 769, 771,
        774, 776, 779, 781, 785, 786, 789, 790, 791, 792, 793, 794, 795,
        796, 799, 801, 802, 803, 804, 805, 806, 808, 809, 810, 811, 812,
        813, 814, 817, 819, 821, 822, 823, 825, 826, 827, 828, 829, 830,
        831, 833, 834, 835, 836, 837, 838, 840, 842, 845, 846, 847, 848,
        849, 851, 852, 853, 855, 861, 862, 863, 864, 865, 866, 868, 869,
        873, 874, 875, 876, 877, 878, 879, 882, 883, 884, 885, 886, 887,
        888, 889, 890, 893, 895, 897, 899, 900, 901, 902, 903, 904, 906,
        907, 909, 910, 912, 913, 915, 916, 918, 919, 920, 925, 926, 927,
        928, 929, 930, 931, 932, 933, 934, 935, 937, 938, 940, 941]),)

In [31]:
len(idx_av_absent[0])

597

## now lets get the data in which murmur is present

### murmur = present

In [32]:
ids_av_present = csv.loc[idx_av_present]['Patient ID'].values
ids_av_present

array([ 9979, 14241, 29045, 40840, 44514, 46065, 49574, 49595, 49627,
       49628, 49691, 49712, 49748, 49754, 49821, 49824, 49850, 49897,
       49900, 49931, 49994, 50056, 50115, 50129, 50136, 50138, 50150,
       50209, 50220, 50221, 50229, 50233, 50238, 50256, 50260, 50277,
       50280, 50289, 50326, 50331, 50332, 50629, 50676, 50734, 50781,
       50790, 55945, 68194, 68255, 68303, 68306, 68337, 68363, 68374,
       68379, 68425, 68432, 68435, 68444, 68456, 68487, 68560, 68582,
       68708, 69068, 69079, 69093, 69096, 69147, 73497, 76240, 78280,
       84692, 84693, 84695, 84714, 84718, 84751, 84802, 84834, 84854,
       84857, 84863, 84864, 84865, 84885, 84896, 84949, 85002, 85024,
       85031, 85036, 85055, 85057, 85079, 85080, 85087, 85110, 85119,
       85133, 85165, 85169, 85172, 85198, 85207, 85259, 85261, 85306])

In [33]:
len(ids_av_present)

108

In [35]:
np.save(path + "/murmur_present_ids", ids_av_present, allow_pickle = True)

In [36]:
ids_av_absent = csv.loc[idx_av_absent]['Patient ID'].values
ids_av_absent

array([ 2530, 14998, 23625, 24160, 31737, 38337, 39043, 39403, 40058,
       40798, 43852, 46532, 49561, 49562, 49568, 49577, 49585, 49598,
       49610, 49622, 49631, 49641, 49653, 49659, 49661, 49678, 49683,
       49687, 49704, 49719, 49729, 49745, 49776, 49829, 49832, 49839,
       49842, 49853, 49854, 49873, 49876, 49896, 49930, 49952, 49959,
       49960, 49963, 49970, 49974, 49980, 49983, 49986, 49987, 49988,
       49990, 49993, 49995, 49999, 50001, 50006, 50007, 50008, 50009,
       50014, 50015, 50017, 50018, 50023, 50026, 50027, 50029, 50034,
       50037, 50043, 50049, 50053, 50061, 50066, 50070, 50074, 50075,
       50076, 50078, 50079, 50080, 50085, 50089, 50092, 50096, 50100,
       50103, 50104, 50109, 50111, 50113, 50126, 50128, 50141, 50142,
       50153, 50155, 50165, 50174, 50204, 50207, 50210, 50213, 50214,
       50216, 50218, 50219, 50225, 50228, 50230, 50231, 50239, 50244,
       50247, 50249, 50250, 50251, 50254, 50255, 50261, 50263, 50264,
       50271, 50272, 50273, 50275, 50276, 50278, 50284, 50291, 50295,
       50296, 50297, 50299, 50303, 50306, 50312, 50314, 50316, 50317,
       50318, 50321, 50323, 50325, 50327, 50334, 50335, 50339, 50341,
       50342, 50343, 50348, 50349, 50350, 50352, 50354, 50359, 50375,
       50379, 50384, 50385, 50386, 50388, 50393, 50619, 50624, 50628,
       50631, 50635, 50643, 50644, 50645, 50646, 50647, 50649, 50652,
       50654, 50655, 50657, 50658, 50659, 50661, 50664, 50667, 50668,
       50669, 50673, 50677, 50680, 50685, 50687, 50688, 50689, 50690,
       50691, 50693, 50699, 50704, 50707, 50708, 50713, 50715, 50720,
       50721, 50723, 50725, 50727, 50729, 50732, 50738, 50739, 50740,
       50742, 50743, 50747, 50748, 50749, 50751, 50752, 50753, 50754,
       50756, 50758, 50762, 50763, 50766, 50768, 50770, 50771, 50772,
       50773, 50774, 50782, 50784, 50788, 50789, 50797, 50798, 50800,
       50802, 50803, 50807, 50812, 50815, 50818, 50819, 50820, 50822,
       50826, 50829, 51331, 59536, 61610, 63456, 63581, 68182, 68186,
       68213, 68219, 68222, 68260, 68292, 68316, 68318, 68327, 68359,
       68368, 68377, 68406, 68407, 68412, 68413, 68419, 68427, 68431,
       68436, 68449, 68460, 68465, 68477, 68478, 68482, 68484, 68498,
       68504, 68532, 68545, 68624, 68632, 68646, 68659, 68660, 68682,
       68698, 68702, 68705, 68711, 68737, 68738, 68741, 68752, 68755,
       68757, 68827, 68849, 68861, 68886, 68887, 68888, 68895, 68901,
       68909, 68952, 69066, 69095, 69106, 69112, 69125, 69129, 69141,
       69144, 69152, 69159, 69161, 69174, 69176, 69188, 70280, 73316,
       74417, 74420, 75440, 78592, 80348, 81297, 81501, 81638, 82275,
       84687, 84689, 84696, 84697, 84699, 84706, 84708, 84709, 84710,
       84711, 84713, 84716, 84721, 84724, 84727, 84733, 84734, 84735,
       84738, 84740, 84742, 84743, 84749, 84750, 84753, 84754, 84758,
       84761, 84762, 84764, 84775, 84776, 84778, 84779, 84780, 84784,
       84785, 84790, 84793, 84796, 84798, 84799, 84803, 84805, 84807,
       84808, 84809, 84813, 84814, 84815, 84822, 84823, 84824, 84826,
       84829, 84831, 84835, 84838, 84839, 84851, 84852, 84856, 84859,
       84861, 84866, 84868, 84870, 84874, 84876, 84877, 84878, 84879,
       84881, 84883, 84884, 84887, 84890, 84893, 84894, 84912, 84917,
       84920, 84921, 84922, 84923, 84928, 84930, 84931, 84933, 84935,
       84936, 84939, 84942, 84945, 84946, 84947, 84952, 84957, 84960,
       84961, 84962, 84965, 84966, 84970, 84973, 84974, 84976, 84977,
       84978, 84982, 84985, 84986, 84987, 84990, 84991, 84992, 84993,
       84994, 84996, 85000, 85010, 85011, 85012, 85018, 85019, 85020,
       85023, 85026, 85027, 85028, 85029, 85033, 85034, 85035, 85038,
       85044, 85046, 85048, 85053, 85062, 85064, 85075, 85077, 85084,
       85086, 85091, 85093, 85094, 85096, 85099, 85100, 85102, 85103,
       85109, 85112, 85113, 85114, 85115, 85116, 85118, 85121, 85122,
       85123, 85124, 85127, 85128, 85131, 85134, 85136, 85140, 85143,
       85144, 85147, 85148, 85150, 85151, 85152, 85153, 85154, 85157,
       85159, 85161, 85162, 85163, 85164, 85166, 85168, 85174, 85175,
       85176, 85180, 85181, 85184, 85186, 85192, 85197, 85210, 85212,
       85213, 85214, 85216, 85217, 85222, 85225, 85230, 85234, 85235,
       85236, 85239, 85240, 85241, 85244, 85245, 85246, 85247, 85249,
       85250, 85252, 85253, 85258, 85262, 85265, 85270, 85277, 85278,
       85279, 85282, 85285, 85286, 85288, 85293, 85296, 85299, 85301,
       85305, 85308, 85312, 85315, 85316, 85317, 85326, 85327, 85328,
       85329, 85331, 85332, 85334, 85335, 85336, 85337, 85338, 85340,
       85341, 85345, 85349])

In [37]:
len(ids_av_absent)

597

In [38]:
np.save(path + "murmur_absent_ids", ids_av_absent, allow_pickle = True)