In [1]:
import pandas as pd 
from scipy.stats import mannwhitneyu
from scipy import stats
import numpy as np

In [2]:
AV_path =  "/Users/ecem/Desktop/phonocardiogram/data/AV/present"
MV_path =  "/Users/ecem/Desktop/phonocardiogram/data/MV/present"
PV_path =  "/Users/ecem/Desktop/phonocardiogram/data/PV/present"
TV_path =  "/Users/ecem/Desktop/phonocardiogram/data/TV/present"

# Time domain features

In [3]:
av = pd.read_csv(AV_path + "/AV-bandpower-and-peaks.csv", index_col = 0)
mv = pd.read_csv(MV_path + "/MV-bandpower-and-peaks.csv", index_col = 0)
pv = pd.read_csv(PV_path + "/PV-bandpower-and-peaks.csv", index_col = 0)
tv = pd.read_csv(TV_path + "/TV-bandpower-and-peaks.csv", index_col = 0)

In [4]:
av

,peak max,peak min,0'th bandpower,1'th bandpower,2'th bandpower,3'th bandpower,4'th bandpower,5'th bandpower,6'th bandpower,7'th bandpower,...,19'th bandpower,20'th bandpower,21'th bandpower,22'th bandpower,23'th bandpower,24'th bandpower,25'th bandpower,26'th bandpower,27'th bandpower,28'th bandpower
0,0.032980,0.010268,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000261,9.663655e-05,3.411161e-05,7.327356e-07,6.109667e-12,6.990118e-13,1.567410e-13,3.271238e-14,7.560295e-15,9.672206e-16
1,0.023604,0.010027,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000012,1.519768e-06,2.062811e-06,1.606117e-07,1.665456e-12,2.279566e-13,5.451163e-14,1.162113e-14,2.702502e-15,3.390508e-16
2,0.023554,0.010067,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000003,1.994108e-07,3.527831e-07,2.466588e-08,5.443871e-13,9.449346e-14,2.406857e-14,5.290868e-15,1.248620e-15,1.559593e-16
3,0.020444,0.010010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000006,1.912566e-07,8.166079e-07,8.318966e-08,1.157595e-12,1.613553e-13,4.033335e-14,8.847740e-15,2.087383e-15,2.573168e-16
4,0.027402,0.010116,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000003,2.382790e-07,1.307754e-06,2.114730e-07,1.824674e-12,2.502706e-13,6.282048e-14,1.378203e-14,3.249271e-15,4.029512e-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1240,0.017813,0.010050,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000012,1.664215e-05,1.938583e-05,4.073607e-07,8.039866e-12,1.191955e-12,3.142340e-13,7.145767e-14,1.715707e-14,2.102312e-15
1241,0.020770,0.010154,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000035,2.797283e-05,2.315478e-05,4.149988e-07,1.220111e-11,2.185165e-12,5.825090e-13,1.321406e-13,3.165776e-14,3.874504e-15
1242,0.019868,0.010116,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000016,3.136179e-05,3.635865e-05,4.119947e-07,1.874447e-11,2.387235e-12,5.923508e-13,1.317217e-13,3.139730e-14,3.890403e-15
1243,0.014941,0.010130,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000034,3.198132e-05,3.773080e-05,7.000800e-07,1.568361e-11,2.524729e-12,6.682197e-13,1.516126e-13,3.636161e-14,4.466815e-15
1244,0.017711,0.010448,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000091,2.756117e-05,2.258972e-05,7.148218e-07,2.624054e-11,5.652342e-12,1.563488e-12,3.592980e-13,8.654061e-14,1.062161e-14

### AV-MV

In [5]:
test = mannwhitneyu(av, mv,
                    use_continuity=False, alternative = 'two-sided')
stats = pd.DataFrame(test[0])
p = pd.DataFrame(test[1])

In [6]:
p.T.style.apply(lambda x: ["background: pink" if v < 0.05 else "" for v in x], axis = 1)

In [7]:
av_mv = p[(p < 0.05).any(axis=1)].index
av_mv

Int64Index([0, 1, 20, 21, 25, 26, 27, 28, 29, 30], dtype='int64')

### AV-PV

In [8]:
test = mannwhitneyu(av, pv, use_continuity=False, alternative = 'two-sided')
stats = pd.DataFrame(test[0])
p = pd.DataFrame(test[1])

av_pv = p[(p < 0.05).any(axis=1)].index

print(av_pv)

Int64Index([1, 19, 22, 23, 24, 26, 27, 28, 29, 30], dtype='int64')

In [9]:
p.T.style.apply(lambda x: ["background: pink" if v < 0.05 else "" for v in x], axis = 1)

### AV-TV

In [10]:
test = mannwhitneyu(av, tv, use_continuity=False, alternative = 'two-sided')
stats = pd.DataFrame(test[0])
p = pd.DataFrame(test[1])

p.T.style.apply(lambda x: ["background: pink" if v < 0.05 else "" for v in x], axis = 1)

av_tv = p[(p < 0.05).any(axis=1)].index

print(av_tv)

Int64Index([0, 1, 22, 23, 25, 26, 27, 28, 29, 30], dtype='int64')

In [11]:
p.T.style.apply(lambda x: ["background: pink" if v < 0.05 else "" for v in x], axis = 1)

In [12]:
list(set(av_mv) & set(av_pv) & set(av_tv))

[1, 26, 27, 28, 29, 30]

### MV-PV

In [13]:
test = mannwhitneyu(mv, pv, use_continuity=False, alternative = 'two-sided')
stats = pd.DataFrame(test[0])
p = pd.DataFrame(test[1])


mv_pv = p[(p < 0.05).any(axis=1)].index

print(mv_pv)

Int64Index([0, 19, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30], dtype='int64')

In [14]:
p.T.style.apply(lambda x: ["background: pink" if v < 0.05 else "" for v in x], axis = 1)

### MV_TV

In [15]:
test = mannwhitneyu(mv, tv, use_continuity=False, alternative = 'two-sided')
stats = pd.DataFrame(test[0])
p = pd.DataFrame(test[1])

mv_tv = p[(p < 0.05).any(axis=1)].index

print(mv_tv)

Int64Index([1, 22, 25, 26, 27, 28, 29, 30], dtype='int64')

In [16]:
p.T.style.apply(lambda x: ["background: pink" if v < 0.05 else "" for v in x], axis = 1)

In [17]:
list(set(mv_tv) & set(mv_pv))

[22, 25, 26, 27, 28, 29, 30]

### PV-TV

In [18]:
test = mannwhitneyu(pv, tv, use_continuity=False, alternative = 'two-sided')
stats = pd.DataFrame(test[0])
p = pd.DataFrame(test[1])

pv_tv = p[(p < 0.05).any(axis=1)].index

print(pv_tv)

Int64Index([0, 1, 19, 22, 23, 24], dtype='int64')

In [19]:
p.T.style.apply(lambda x: ["background: pink" if v < 0.05 else "" for v in x], axis = 1)

In [20]:
df = pd.concat([av, mv, pv, tv], axis =0)
df.head()

,peak max,peak min,0'th bandpower,1'th bandpower,2'th bandpower,3'th bandpower,4'th bandpower,5'th bandpower,6'th bandpower,7'th bandpower,...,19'th bandpower,20'th bandpower,21'th bandpower,22'th bandpower,23'th bandpower,24'th bandpower,25'th bandpower,26'th bandpower,27'th bandpower,28'th bandpower
0,0.032980,0.010268,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000261,9.663655e-05,3.411161e-05,7.327356e-07,6.109667e-12,6.990118e-13,1.567410e-13,3.271238e-14,7.560295e-15,9.672206e-16
1,0.023604,0.010027,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000012,1.519768e-06,2.062811e-06,1.606117e-07,1.665456e-12,2.279566e-13,5.451163e-14,1.162113e-14,2.702502e-15,3.390508e-16
2,0.023554,0.010067,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000003,1.994108e-07,3.527831e-07,2.466588e-08,5.443871e-13,9.449346e-14,2.406857e-14,5.290868e-15,1.248620e-15,1.559593e-16
3,0.020444,0.010010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000006,1.912566e-07,8.166079e-07,8.318966e-08,1.157595e-12,1.613553e-13,4.033335e-14,8.847740e-15,2.087383e-15,2.573168e-16
4,0.027402,0.010116,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000003,2.382790e-07,1.307754e-06,2.114730e-07,1.824674e-12,2.502706e-13,6.282048e-14,1.378203e-14,3.249271e-15,4.029512e-16

In [21]:
indexes = [0, 1, 21, 25, 26, 27, 28, 29]

In [22]:
df = df.iloc[:, indexes]

In [23]:
df

,peak max,peak min,19'th bandpower,23'th bandpower,24'th bandpower,25'th bandpower,26'th bandpower,27'th bandpower
0,0.032980,0.010268,0.000261,6.109667e-12,6.990118e-13,1.567410e-13,3.271238e-14,7.560295e-15
1,0.023604,0.010027,0.000012,1.665456e-12,2.279566e-13,5.451163e-14,1.162113e-14,2.702502e-15
2,0.023554,0.010067,0.000003,5.443871e-13,9.449346e-14,2.406857e-14,5.290868e-15,1.248620e-15
3,0.020444,0.010010,0.000006,1.157595e-12,1.613553e-13,4.033335e-14,8.847740e-15,2.087383e-15
4,0.027402,0.010116,0.000003,1.824674e-12,2.502706e-13,6.282048e-14,1.378203e-14,3.249271e-15
...,...,...,...,...,...,...,...,...
1200,0.021617,0.010008,0.000009,3.835486e-11,9.581233e-12,2.714072e-12,6.293829e-13,1.521620e-13
1201,0.016234,0.010121,0.000012,3.461051e-11,8.612623e-12,2.450093e-12,5.694388e-13,1.378679e-13
1202,0.020612,0.010439,0.000007,4.692765e-11,1.176325e-11,3.336666e-12,7.740218e-13,1.871832e-13
1203,0.015761,0.010131,0.000030,3.649793e-11,8.348918e-12,2.341760e-12,5.415036e-13,1.306791e-13
1204,0.020985,0.010072,0.000039,3.207894e-11,7.526305e-12,2.120560e-12,4.913675e-13,1.186663e-13

In [24]:
df.to_csv("/Users/ecem/Desktop/phonocardiogram/data/bandpower.csv")